set(CMAKE_CXX_FLAGS_RELEASE		"-O3 -march=native")
set(CMAKE_C_FLAGS_RELEASE		"-O3 -march=native")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0 -Wall")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1y -Wall")

if(NOT DEFINED EXECUTABLE_OUTPUT_PATH)
	set(EXECUTABLE_OUTPUT_PATH 		"${CMAKE_BINARY_DIR}/bin")
endif(NOT DEFINED EXECUTABLE_OUTPUT_PATH)

if(NOT DEFINED LIBRARY_OUTPUT_PATH)
	set(LIBRARY_OUTPUT_PATH 		"${CMAKE_BINARY_DIR}/lib")
endif(NOT DEFINED LIBRARY_OUTPUT_PATH)

if(NOT DEFINED CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE			"Release")
endif(NOT DEFINED CMAKE_BUILD_TYPE)
